### ISSUE TITLE
Fire TV MQA Enabled doesn't work.

### ISSUE THREAD

**Issue by AldenBluetenberger** [openTIDAL/docTIDAL#1]

**Comment by hmelder** [comment]
Nope it works. Keep in mind that the login/username endpoint is deprecated. Read the Wiki!
![Screenshot 2020-10-18 at 19 31 09](https://user-images.githubusercontent.com/45601940/96375307-87619880-1178-11eb-9f88-aa5657f8ec3b.png)
![Screenshot 2020-10-18 at 19 32 33](https://user-images.githubusercontent.com/45601940/96375325-b0822900-1178-11eb-9d9c-6e656e92f0a5.png)
