### ISSUE TITLE
How can I get a client id?

### ISSUE THREAD

**Issue by Hasintha-Jayasinghe** [openTIDAL/docTIDAL#3]
I can't seem to find the page where you describe how to find the client id... it could be that i didn't search properly (very good chance)

**Comment by charleywright** [comment]
[This](https://github.com/Fokka-Engineering/TIDAL/wiki/Copyright) page explains why they are not listed. To get your own, either [take them from someone's source](https://github.com/nathom/streamrip/blob/main/streamrip/constants.py) or dump them yourself by using a proxy.

Edit: I made a list of some [here](https://gist.github.com/charleywright/59c14e083177619d8cc9630d7f468690)
