### ISSUE TITLE
Api changes 11.2021 old cliendId fire doesn't work

### ISSUE THREAD

**Issue by Mr-Negative** [openTIDAL/docTIDAL#4]
Since two days authentication via /device_authorization and cliendId of fire tv
throws this error
`"status":401,"error":"invalid_client","error_description":"Client with token   ********XOEP not found"`

Any chance to look into it and finding new Id? You seem like person most equipped for this task, watching this documentation and how good and precise it is.

**Comment by charleywright** [comment]
Tidal didn't just change the ID, I don't have a fire stick so I've been reversing the android/ios apps and desktop app. So far I am back to being able to authenticate and get stream URL's, but everything has `"encryptionType": "OLD_AES"` with a `keyId` that is a base64 string.

**Comment by Mr-Negative** [comment]
@charleywright 
Do you download as flac/master/ normal? because i've tried and sniffing and it was using completly different algoritms, manifest using base64 encoded xml, etc.
 if you menaged to get to everything have keyId, then it maybe should work with https://github.com/yaronzz/Tidal-Media-Downloader/ - it has decoding part that use aes and keyId exactly for this purpose. I suspect maybe older files can have this setup.

**Comment by Mr-Negative** [comment]
Edit. Closing issue. In other place they figured it out
