### ISSUE TITLE
track contributors endpoint returns a 404 error: {"status":404,"subStatus":2001,"userMessage":"Resource not found"}

### ISSUE THREAD

**Issue by trustosas** [openTIDAL/docTIDAL#5]
The track contributors endpoint is not working for me. The error is in the description. I'm quite new to this repo but all the endpoints I've tested so far work fine. What is the issue here?

**Comment by hmelder** [comment]
Hi,

Maybe there are no contributors available for the track? Have you tried it with other artefacts?

**Comment by trustosas** [comment]
My bad. My code was the problem. It works now.
